[project]
name = "velodata-discord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "fastapi>=0.115.6",
    "python-dotenv>=1.0.1",
]
